DROP SEQUENCE SEC_CLINICAS;
DROP SEQUENCE SEC_TRABAJAEN;
DROP SEQUENCE SEC_CITAS;
DROP SEQUENCE SEC_LINEASDEHISTORIAL;


DROP TABLE LINEASDEHISTORIAL;
DROP TABLE HISTORIALES;
DROP TABLE CITAS;
DROP TABLE PACIENTES;
DROP TABLE TRABAJAEN;
DROP TABLE TRABAJADORES;
DROP TABLE CLINICAS;
DROP TABLE RECEPCIONISTAS;
DROP TABLE MEDICOS;


--CREACIÓN DE TABLAS
CREATE TABLE CLINICAS
  (OID_CLINICA NUMBER NOT NULL,
  NOMBRE_CLINICA VARCHAR2(100)NOT NULL,
  DIRECCION VARCHAR2(100) NOT NULL,
  PRIMARY KEY (OID_CLINICA));
  
CREATE TABLE RECEPCIONISTAS
  (USUARIO VARCHAR2(75) PRIMARY KEY,
  CONTRASEÑA VARCHAR2(75) NOT NULL,
  NOMBRE VARCHAR2(40) NOT NULL,
  APELLIDOS VARCHAR2(40) NOT NULL,
  DNI CHAR(9) NOT NULL UNIQUE,
  EMAIL VARCHAR2(40) NOT NULL,
  TELEFONO VARCHAR2(9) NOT NULL);

CREATE TABLE TRABAJADORES
  (DNI CHAR(9) PRIMARY KEY,
  NOMBRE VARCHAR2(30) NOT NULL,
  APELLIDOS VARCHAR2(40) NOT NULL,
  EMAIL VARCHAR2(40) NOT NULL ,
  OID_CLINICA NUMBER NOT NULL,
  FOREIGN KEY(OID_CLINICA) REFERENCES CLINICAS(OID_CLINICA));
  
CREATE TABLE MEDICOS
  (USUARIO_MEDICO VARCHAR2(75) PRIMARY KEY,
  CONTRASEÑA VARCHAR2(75) NOT NULL,
  NOMBRE VARCHAR2(40) NOT NULL,
  APELLIDOS VARCHAR2(40) NOT NULL,
  DNI CHAR(9) NOT NULL UNIQUE,
  EMAIL VARCHAR2(40) NOT NULL,
  ESPECIALIDAD VARCHAR2(40) NOT NULL,
  MAXNUMCITAS NUMBER(3) NOT NULL);
  
CREATE TABLE TRABAJAEN
  (OID_TE NUMBER(2) PRIMARY KEY,
  USUARIO_MEDICO VARCHAR2(75) NOT NULL,
  OID_CLINICA NUMBER NOT NULL,
  FOREIGN KEY(USUARIO_MEDICO) REFERENCES MEDICOS(USUARIO_MEDICO),
  FOREIGN KEY(OID_CLINICA) REFERENCES CLINICAS(OID_CLINICA));
  
CREATE TABLE PACIENTES
  (DNI CHAR(9) PRIMARY KEY,
  NOMBRE VARCHAR2(40) NOT NULL,
  APELLIDOS VARCHAR2(40) NOT NULL,
  EMAIL VARCHAR2(40) NOT NULL,
  NUMEROSEGURO NUMBER(6),
  USUARIO_RECEPCIONISTA VARCHAR2(75)NOT NULL,
  FOREIGN KEY(USUARIO_RECEPCIONISTA) REFERENCES RECEPCIONISTAS(USUARIO));
  
CREATE TABLE CITAS
  (OID_CITA NUMBER PRIMARY KEY,
  HORA VARCHAR2(5) NOT NULL,
  FECHA DATE NOT NULL,
  OID_CLINICA NUMBER,
  USUARIO_MEDICO VARCHAR2(75) NOT NULL,
  USUARIO_RECEPCIONISTA VARCHAR2(75),
  DNI_PACIENTE CHAR(9),
  FOREIGN KEY(OID_CLINICA) REFERENCES CLINICAS(OID_CLINICA),
  FOREIGN KEY(USUARIO_MEDICO) REFERENCES MEDICOS(USUARIO_MEDICO),
  FOREIGN KEY(USUARIO_RECEPCIONISTA) REFERENCES RECEPCIONISTAS(USUARIO),
  FOREIGN KEY(DNI_PACIENTE) REFERENCES PACIENTES(DNI));
  
CREATE TABLE HISTORIALES
  (CODIGO VARCHAR2(6) PRIMARY KEY,
  NOMBREPACIENTE VARCHAR2(40) NOT NULL,
  APELLIDOSPACIENTE VARCHAR2(60) NOT NULL,
  USUARIO_MEDICO VARCHAR2(75),
  DNI_PACIENTE CHAR(9),
  FOREIGN KEY (USUARIO_MEDICO) REFERENCES MEDICOS(USUARIO_MEDICO),
  FOREIGN KEY (DNI_PACIENTE) REFERENCES PACIENTES(DNI));
  
CREATE TABLE LINEASDEHISTORIAL
  (OID_LH NUMBER PRIMARY KEY,
  FECHA DATE NOT NULL,
  OBSERVACIONES VARCHAR2(400) NOT NULL,
  CODIGO_HISTORIAL VARCHAR2(6) NOT NULL,
  FOREIGN KEY (CODIGO_HISTORIAL) REFERENCES HISTORIALES(CODIGO) ON DELETE CASCADE);
  
  
--RESTRICCIONES DE TABLAS
ALTER TABLE RECEPCIONISTAS ADD CONSTRAINT CK_DNI_RECEPCIONISTAS CHECK (REGEXP_LIKE(DNI, '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][A-Z]'));
ALTER TABLE TRABAJADORES ADD CONSTRAINT CK_DNI_TRABAJADORES CHECK (REGEXP_LIKE(DNI, '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][A-Z]'));
ALTER TABLE MEDICOS ADD CONSTRAINT CK_DNI_MEDICOS CHECK (REGEXP_LIKE(DNI, '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][A-Z]'));
ALTER TABLE PACIENTES ADD CONSTRAINT CK_DNI_PACIENTES CHECK (REGEXP_LIKE(DNI, '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][A-Z]'));
ALTER TABLE CITAS ADD CONSTRAINT CK_DNI_CITAS CHECK (REGEXP_LIKE(DNI_PACIENTE,'[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][A-Z]')OR DNI_PACIENTE IS NULL);
ALTER TABLE HISTORIALES ADD CONSTRAINT CK_DNI_HISTORIALES CHECK (REGEXP_LIKE(DNI_PACIENTE, '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][A-Z]'));
ALTER TABLE PACIENTES ADD CONSTRAINT CK_NUMEROSEGURO_PACIENTES CHECK (REGEXP_LIKE(NUMEROSEGURO, '[0-9][0-9][0-9][0-9][0-9][0-9]')OR NUMEROSEGURO IS NULL);
ALTER TABLE HISTORIALES ADD CONSTRAINT CK_CÓDIGO_HISTORIALES CHECK (REGEXP_LIKE(CODIGO, '[0-9][0-9][0-9][0-9][0-9][0-9]'));
ALTER TABLE LINEASDEHISTORIAL ADD CONSTRAINT CK_CÓDIGO_LINEASDEHISTORIAL CHECK (REGEXP_LIKE(CODIGO_HISTORIAL, '[0-9][0-9][0-9][0-9][0-9][0-9]'));
ALTER TABLE MEDICOS ADD CONSTRAINT CK_ESPECIALIDAD_MÉDICOS CHECK (ESPECIALIDAD IN ('ONCÓLOGO', 'GINECÓLOGO', 'EMBRIÓLOGO','ANESTESISTA'));
ALTER TABLE CITAS ADD CONSTRAINT CK_HORA_CITAS CHECK (REGEXP_LIKE(Hora, '[0-2][0-9]:[0-5][0-9]'));

--SECUENCIAS
CREATE SEQUENCE SEC_CLINICAS INCREMENT BY 1 START WITH 1 MAXVALUE 99999;
CREATE SEQUENCE SEC_TRABAJAEN INCREMENT BY 1 START WITH 1 MAXVALUE 99999;
CREATE SEQUENCE SEC_CITAS INCREMENT BY 1 START WITH 1 MAXVALUE 99999;
CREATE SEQUENCE SEC_LINEASDEHISTORIAL INCREMENT BY 1 START WITH 1 MAXVALUE 99999;

--TRIGGERS ASOCIADOS A SECUENCIAS
CREATE OR REPLACE TRIGGER TR_SEC_CLINICAS
  BEFORE INSERT ON CLINICAS 
  FOR EACH ROW 
  BEGIN 
    SELECT SEC_CLINICAS.NEXTVAL INTO :NEW.OID_CLINICA FROM DUAL; 
  END;
/
CREATE OR REPLACE TRIGGER TR_SEC_TRABAJAEN
  BEFORE INSERT ON TRABAJAEN 
  FOR EACH ROW 
  BEGIN 
    SELECT SEC_TRABAJAEN.NEXTVAL INTO :NEW.OID_TE FROM DUAL; 
  END;
/  
CREATE OR REPLACE TRIGGER TR_SEC_CITAS
  BEFORE INSERT ON CITAS 
  FOR EACH ROW 
  BEGIN 
    SELECT SEC_CITAS.NEXTVAL INTO :NEW.OID_CITA FROM DUAL; 
  END;
/
CREATE OR REPLACE TRIGGER TR_SEC_LINEASDEHISTORIAL
  BEFORE INSERT ON LINEASDEHISTORIAL 
  FOR EACH ROW 
  BEGIN 
    SELECT SEC_LINEASDEHISTORIAL.NEXTVAL INTO :NEW.OID_LH FROM DUAL; 
  END;
/